# Generated by Django 4.1.7 on 2023-02-21 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_remove_csvfileuplaod_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CsvFileUplaod',
        ),
    ]
