# Generated by Django 4.1.7 on 2023-02-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_alter_trading_close_alter_trading_high_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trading',
            name='DATE',
            field=models.CharField(max_length=50),
        ),
    ]
