# Generated by Django 4.1.7 on 2023-02-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_alter_trading_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trading',
            name='TIME',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trading',
            name='VOLUME',
            field=models.CharField(max_length=50),
        ),
    ]
