# Generated by Django 4.1.7 on 2023-02-21 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_alter_trading_time_alter_trading_volume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trading',
        ),
    ]
